# Generated by Django 5.1.15 on 2026-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardstatus',
            name='collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardstatus',
            name='is_collapsible',
            field=models.BooleanField(default=False),
        ),
    ]
