# Generated by Django 5.1.15 on 2026-08-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('default', 'Default'), ('purple', 'Purple'), ('blue', 'Blue'), ('teal', 'Teal'), ('red', 'Red')], default='default', max_length=16),
        ),
    ]
